# fly.toml app configuration file generated for policycheck-d7wv0g on 2026-02-14T14:58:05Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'policycheck-d7wv0g'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
